### ISSUE TITLE
[Feature] Add '--help' into cli commands

### ISSUE THREAD

**Issue by shunia** [weaigc/gradio-chatbot#1]
I have to go through some source code to find out how to target to a specific model in `cli` mode, which if a '--help' is provided could be really helpful.
Or simply add a example for how to specify modelin README could be enough.

And for anyone don't know yet, you can target the chat-bot you want by add the model index after the command like: 
```
npx gradio-chatbot 2 // which will target the 'Falcon Chat' listed in the repo's README
```

And if you are using pnpm, you should call the command like:
```
pnpm --package=gradio-chatbot dlx chatbot 2
```

**Comment by weaigc** [comment]
> I have to go through some source code to find out how to target to a specific model in `cli` mode, which if a '--help' is provided could be really helpful. Or simply add a example for how to specify modelin README could be enough.
> 
> And for anyone don't know yet, you can target the chat-bot you want by add the model index after the command like:
> 
> ```
> npx gradio-chatbot 2 // which will target the 'Falcon Chat' listed in the repo's README
> ```
> 
> And if you are using pnpm, you should call the command like:
> 
> ```
> pnpm --package=gradio-chatbot dlx chatbot 2
> ```

To view the help, simply enter "npx gradio-chatbot help". It is mentioned in the documentation, it may not be prominently displayed. Let me make that clearer.
