### ISSUE TITLE
localhost:8000 not loading the UI page

### ISSUE THREAD

**Issue by datacrud8** [weaigc/gradio-chatbot#5]
actual script dont have "dev", I have add like below then start with npm run dev

 "scripts": {
    "build": "rimraf -rf ./dist && tsc -p ./",
    "test": "tsx ./tests/index",
    "dev":"tsx ./src/bin/server.ts",
    "debug": "cross-env DEBUG=gradio-chatbot tsx ./src/bin/cli.ts",
    "prepublishOnly": "npm run build"
  },

server started and seeing this below message but in the browser not loading anything.

> gradio-chatbot@0.0.15 start
> tsx ./src/bin/server.ts

Server start successful, serve link: http://localhost:8000/api/conversation?text=hello

Can you please update correct script , or tell me how run this project in local?
I need to check out then code, then  npm build then want run in local , not for install. Can you tell me the correct script update.

**Comment by weaigc** [comment]
@datacrud8 Done

**Comment by datacrud8** [comment]
No, this is wrong script "dev":"tsx ./src/bin/server.ts", you can see server message like this 
Server start successful, serve link: http://localhost:8000/api/conversation?text=hello
but page NOT loading anything, its empty screen.

So What is correct script to run this application in http://localhost:8000/ ?
