### ISSUE TITLE
您好，关于API有些问题

### ISSUE THREAD

**Issue by 15899885850** [weaigc/gradio-chatbot#6]
您好！
我是一名新手，现在我在一个云服务器上搭建了llama2，并且使用text-generation-webui的项目实现了一个webui的界面，最后我也获得了一个公网可以访问我自己搭建的llama2的服务的地址。
现在我希望，在有这个地址的情况下，能不能实现一个公共的api，也就是借助我在云服务器上搭建好的服务，其他电脑可以通过一个公共的api来获取这个服务。
希望得到您的回复，谢谢！

**Comment by weaigc** [comment]
@15899885850 你可以看看这个项目
https://github.com/hyperonym/basaran
